apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "atharva.k.kumbhar@slrtce.in" #enter your email to get the id
  GMAIL_PASSWORD: "fgfp tbxw yisg kabo"
type: Opaque

# Passw0rd@1234
